services:
  postgres:
    image: postgres:15
    container_name: postgres-taskdb
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 0002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: spring-task-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 0002
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
